# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_Q_grid <- function(n = 10L) {
    .Call(`_VoA_create_Q_grid`, n)
}

Q <- function(Q_grid, C_grid) {
    .Call(`_VoA_Q`, Q_grid, C_grid)
}

seq_int <- function(a, b) {
    .Call(`_VoA_seq_int`, a, b)
}

rnd_idx <- function(n = 10L) {
    .Call(`_VoA_rnd_idx`, n)
}

bootstrap_samples <- function(n, MC = 100L) {
    .Call(`_VoA_bootstrap_samples`, n, MC)
}

arma_copula_mc <- function(Rx, Ry, MC = 100L) {
    .Call(`_VoA_arma_copula_mc`, Rx, Ry, MC)
}

arma_copula <- function(Rx, Ry) {
    .Call(`_VoA_arma_copula`, Rx, Ry)
}

calculate_copula_grid <- function(X, Y) {
    .Call(`_VoA_calculate_copula_grid`, X, Y)
}

calculate_copula_mc_grid <- function(X, Y, MC) {
    .Call(`_VoA_calculate_copula_mc_grid`, X, Y, MC)
}

